import streamlit as st
import pandas as pd
import plotly.express as px
from datetime import datetime

# --- 1. 语言包配置 (Language Config) ---
TRANSLATIONS = {
    "cn": {
        "title": "🛡️ 客户保单年度检视报告",
        "sidebar_title": "🔧 工具箱",
        "lang_select": "选择语言 (Language)",
        "client_profile": "👤 客户档案",
        "client_name": "客户姓名",
        "client_age": "年龄",
        "add_policy_header": "➕ 添加保单",
        "policy_name": "保单名称/计划",
        "policy_company": "保险公司",
        "benefits_label": "🛡️ 选择保单包含的利益 (可多选)",
        "benefits_options": [
            "人寿 (Life)",
            "医药卡 (Medical Card)",
            "36种严重疾病 (36 CI)",
            "106种严重疾病-初期 (106 CI)",
            "157种严重疾病-初期 (157 CI)",
            "个人意外 (PA)",
            "保费豁免 (Waiver)"
        ],
        "premium": "年缴保费 (RM)",
        "coverage": "人寿/重疾保额 (RM)",
        "medical_limit": "医药卡年限额 (RM) (如有)",
        "sustainability": "保单持久性 (可维持至多少岁)",
        "max_age": "最高续保年龄 (至多少岁)",
        "remarks": "备注 (如: Cash Value / 缺口)",
        "add_btn": "📥 添加此保单",
        "clear_btn": "🗑️ 清空列表",
        "report_header": "📊 年度检视分析",
        "total_premium": "年度总保费支出",
        "total_coverage": "总人寿/重疾保障",
        "table_header": "🔎 现有保单明细",
        "chart_title": "各保单投入 vs 保障分析",
        "download_header": "💾 保存/下载",
        "download_btn": "📥 下载检视报告 (Excel/CSV)",
        "footer": "专业顾问年度服务 | Generated by E&S Agency Tool",
        "empty_msg": "👈 请在左侧侧边栏添加保单以生成报告。"
    },
    "en": {
        "title": "🛡️ Annual Policy Review Report",
        "sidebar_title": "🔧 Toolbox",
        "lang_select": "Language",
        "client_profile": "👤 Client Profile",
        "client_name": "Client Name",
        "client_age": "Age",
        "add_policy_header": "➕ Add Policy",
        "policy_name": "Policy Name/Plan",
        "policy_company": "Company",
        "benefits_label": "🛡️ Select Benefits Included (Multi-select)",
        "benefits_options": [
            "Life",
            "Medical Card",
            "36 Critical Illnesses",
            "106 CI (Early Payout)",
            "157 CI (Early Payout)",
            "Personal Accident",
            "Premium Waiver"
        ],
        "premium": "Annual Premium (RM)",
        "coverage": "Life/CI Sum Assured (RM)",
        "medical_limit": "Medical Annual Limit (RM)",
        "sustainability": "Sustainability (Up to Age)",
        "max_age": "Max Coverage Age",
        "remarks": "Remarks (e.g. Cash Value)",
        "add_btn": "📥 Add to List",
        "clear_btn": "🗑️ Clear All",
        "report_header": "📊 Review Analysis",
        "total_premium": "Total Annual Premium",
        "total_coverage": "Total Life/CI Coverage",
        "table_header": "🔎 Policy Details",
        "chart_title": "Premium vs Coverage Analysis",
        "download_header": "💾 Save Report",
        "download_btn": "📥 Download Report (Excel/CSV)",
        "footer": "Professional Annual Review | Generated by E&S Agency Tool",
        "empty_msg": "👈 Please add policies from the sidebar to generate report."
    }
}

st.set_page_config(page_title="Policy Review Tool", page_icon="📝", layout="wide")

# --- 2. 初始化 Session State ---
if 'policies' not in st.session_state:
    st.session_state.policies = []

# --- 3. 侧边栏：输入区 ---
with st.sidebar:
    lang_code = st.radio("Language / 语言", ["中文", "English"], horizontal=True)
    lang = "cn" if lang_code == "中文" else "en"
    t = TRANSLATIONS[lang]

    st.title(t["sidebar_title"])
    
    # 客户资料
    st.header(t["client_profile"])
    c_name = st.text_input(t["client_name"], placeholder="Mr. / Ms.")
    c_age = st.number_input(t["client_age"], min_value=0, max_value=100, value=30)
    
    st.markdown("---")
    
    # 添加保单表单
    st.header(t["add_policy_header"])
    
    with st.form("add_policy_form", clear_on_submit=True):
        p_name = st.text_input(t["policy_name"])
        p_company = st.selectbox(t["policy_company"], ["Allianz", "AIA", "Prudential", "Great Eastern", "Zurich", "Hong Leong", "Takaful", "Other"])
        
        # --- 新增：利益多选框 ---
        p_benefits = st.multiselect(t["benefits_label"], t["benefits_options"])
        
        col_sb1, col_sb2 = st.columns(2)
        with col_sb1:
            p_prem = st.number_input(t["premium"], min_value=0.0, step=100.0)
            # 如果选了医药卡，提醒输入限额，否则通常是0
            p_med_limit = st.number_input(t["medical_limit"], min_value=0.0, step=10000.0, help="Annual Limit")
        with col_sb2:
            p_cov = st.number_input(t["coverage"], min_value=0.0, step=1000.0)
            p_sust = st.number_input(t["sustainability"], min_value=0, max_value=100)
            
        p_max_age = st.number_input(t["max_age"], min_value=0, max_value=100, value=80)
        p_rem = st.text_area(t["remarks"], height=60)
        
        submitted = st.form_submit_button(t["add_btn"])
        
        if submitted:
            if p_name:
                # 将选中的利益列表转换成字符串，例如 "人寿, 医药卡"
                benefits_str = ", ".join(p_benefits)
                
                st.session_state.policies.append({
                    t["policy_name"]: p_name,
                    t["policy_company"]: p_company,
                    "Benefits / 利益": benefits_str, # 新列名
                    t["premium"]: p_prem,
                    t["coverage"]: p_cov,
                    t["medical_limit"]: p_med_limit, # 新增医药卡限额列
                    t["sustainability"]: p_sust if p_sust > 0 else "-",
                    t["max_age"]: p_max_age,
                    t["remarks"]: p_rem
                })
                st.success("✅ Added!")
            else:
                st.error("Please enter policy name.")

    # 清空按钮
    if len(st.session_state.policies) > 0:
        if st.button(t["clear_btn"]):
            st.session_state.policies = []
            st.rerun()

# --- 4. 主界面：报告显示 ---
st.title(f"{t['title']}")
if c_name:
    st.subheader(f"{t['client_profile']}: {c_name} ({c_age})")
st.markdown(f"Date: {datetime.now().strftime('%Y-%m-%d')}")
st.markdown("---")

if len(st.session_state.policies) == 0:
    st.info(t["empty_msg"])

else:
    df = pd.DataFrame(st.session_state.policies)
    
    # 顶部关键指标
    col1, col2, col3, col4 = st.columns(4)
    total_prem = df[t["premium"]].sum()
    total_cov = df[t["coverage"]].sum()
    total_med = df[t["medical_limit"]].sum() # 计算总医疗限额
    
    with col1:
        st.metric(label=t["total_premium"], value=f"RM {total_prem:,.0f}")
    with col2:
        st.metric(label=t["total_coverage"], value=f"RM {total_cov:,.0f}")
    with col3:
        st.metric(label="Total Medical Limit", value=f"RM {total_med:,.0f}", help="所有医药卡年限额总和")
    with col4:
        st.metric(label="Policies", value=len(df))
        
    # --- 表格展示 ---
    st.subheader(t["table_header"])
    
    # 定义列的显示格式
    column_config = {
        t["premium"]: st.column_config.NumberColumn(format="RM %.0f"),
        t["coverage"]: st.column_config.NumberColumn(format="RM %.0f"),
        t["medical_limit"]: st.column_config.NumberColumn(format="RM %.0f"),
        "Benefits / 利益": st.column_config.TextColumn(width="medium"), # 加宽这一列
    }
    
    st.dataframe(
        df, 
        use_container_width=True, 
        hide_index=True,
        column_config=column_config
    )
    
    # --- 图表分析 ---
    st.subheader(t["chart_title"])
    
    # 准备图表数据：包括保费、人寿保额、医疗限额
    chart_df = df.melt(
        id_vars=[t["policy_name"]], 
        value_vars=[t["premium"], t["coverage"], t["medical_limit"]], 
        var_name="Type", 
        value_name="Value"
    )
    
    # 过滤掉值为0的数据（比如没有医药卡的保单就不显示医药卡柱子）
    chart_df = chart_df[chart_df["Value"] > 0]
    
    fig = px.bar(
        chart_df, 
        x=t["policy_name"], 
        y="Value", 
        color="Type", 
        barmode="group",
        text_auto='.2s',
        # 自定义颜色: 保费(红), 保额(青), 医药卡(蓝)
        color_discrete_map={
            t["premium"]: "#FF6B6B", 
            t["coverage"]: "#4ECDC4",
            t["medical_limit"]: "#45B7D1"
        }
    )
    fig.update_layout(xaxis_title="", yaxis_title="RM")
    st.plotly_chart(fig, use_container_width=True)
    
    # --- 持久性警告 ---
    if pd.to_numeric(df[t["sustainability"]], errors='coerce').sum() > 0:
        st.caption("⚠️ Sustainability Check (持久性检查)")
        sust_df = df[pd.to_numeric(df[t["sustainability"]], errors='coerce') > 0].copy()
        if not sust_df.empty:
            st.bar_chart(sust_df.set_index(t["policy_name"])[t["sustainability"]])

    # --- 下载区域 ---
    st.markdown("---")
    csv = df.to_csv(index=False).encode('utf-8')
    file_name = f"Review_{c_name}_{datetime.now().strftime('%Y%m%d')}.csv"
    
    st.download_button(
        label=t["download_btn"],
        data=csv,
        file_name=file_name,
        mime='text/csv'
    )

st.caption(t["footer"])
