import streamlit as st
import pandas as pd
import plotly.express as px
from datetime import datetime

# --- 1. 语言包配置 (Language Config) ---
TRANSLATIONS = {
    "cn": {
        "title": "🛡️ 客户保单年度检视报告",
        "sidebar_title": "🔧 工具箱",
        "lang_select": "选择语言 (Language)",
        "client_profile": "👤 客户档案",
        "client_name": "客户姓名",
        "client_age": "年龄",
        "add_policy_header": "➕ 添加保单",
        "policy_name": "保单名称/计划",
        "policy_company": "保险公司",
        "policy_type": "险种类型",
        "premium": "年缴保费 (RM)",
        "coverage": "保障额度 (RM)",
        "sustainability": "保单持久性 (可维持至多少岁)",
        "max_age": "最高续保年龄 (至多少岁)",
        "remarks": "备注 (如: 无理赔奖励/缺口)",
        "add_btn": "📥 添加此保单到列表",
        "clear_btn": "🗑️ 清空所有保单",
        "report_header": "📊 年度检视分析",
        "total_premium": "年度总保费支出",
        "total_coverage": "总身故/重疾保障",
        "table_header": "🔎 现有保单明细",
        "chart_title": "各保单投入 vs 保障分析",
        "download_header": "💾 保存/下载",
        "download_btn": "📥 下载检视报告 (Excel/CSV)",
        "footer": "专业顾问年度服务 | Generated by E&S Agency Tool",
        "types": ["医疗卡 (Medical)", "人寿/重疾 (Life/CI)", "储蓄/年金 (Savings)", "意外 (PA)"],
        "empty_msg": "👈 请在左侧侧边栏添加保单以生成报告。"
    },
    "en": {
        "title": "🛡️ Annual Policy Review Report",
        "sidebar_title": "🔧 Toolbox",
        "lang_select": "Language",
        "client_profile": "👤 Client Profile",
        "client_name": "Client Name",
        "client_age": "Age",
        "add_policy_header": "➕ Add Policy",
        "policy_name": "Policy Name/Plan",
        "policy_company": "Company",
        "policy_type": "Policy Type",
        "premium": "Annual Premium (RM)",
        "coverage": "Coverage Amount (RM)",
        "sustainability": "Sustainability (Up to Age)",
        "max_age": "Max Coverage Age",
        "remarks": "Remarks (e.g. NCB/Gaps)",
        "add_btn": "📥 Add to List",
        "clear_btn": "🗑️ Clear All",
        "report_header": "📊 Review Analysis",
        "total_premium": "Total Annual Premium",
        "total_coverage": "Total Life/CI Coverage",
        "table_header": "🔎 Policy Details",
        "chart_title": "Premium vs Coverage Analysis",
        "download_header": "💾 Save Report",
        "download_btn": "📥 Download Report (Excel/CSV)",
        "footer": "Professional Annual Review | Generated by E&S Agency Tool",
        "types": ["Medical", "Life/CI", "Savings", "PA"],
        "empty_msg": "👈 Please add policies from the sidebar to generate report."
    }
}

st.set_page_config(page_title="Policy Review Tool", page_icon="📝", layout="wide")

# --- 2. 初始化 Session State (用于存储多张保单) ---
if 'policies' not in st.session_state:
    st.session_state.policies = []

# --- 3. 侧边栏：输入区 ---
with st.sidebar:
    # 语言选择
    lang_code = st.radio("Language / 语言", ["中文", "English"], horizontal=True)
    lang = "cn" if lang_code == "中文" else "en"
    t = TRANSLATIONS[lang] # 获取当前语言的字典

    st.title(t["sidebar_title"])
    
    # 客户资料
    st.header(t["client_profile"])
    c_name = st.text_input(t["client_name"], placeholder="Mr. / Ms.")
    c_age = st.number_input(t["client_age"], min_value=0, max_value=100, value=30)
    
    st.markdown("---")
    
    # 添加保单表单
    st.header(t["add_policy_header"])
    
    with st.form("add_policy_form", clear_on_submit=True):
        p_name = st.text_input(t["policy_name"])
        p_company = st.selectbox(t["policy_company"], ["Allianz", "AIA", "Prudential", "Great Eastern", "Zurich", "Hong Leong", "Other"])
        p_type = st.selectbox(t["policy_type"], t["types"])
        
        col_sb1, col_sb2 = st.columns(2)
        with col_sb1:
            p_prem = st.number_input(t["premium"], min_value=0.0, step=100.0)
            p_sust = st.number_input(t["sustainability"], min_value=0, max_value=100, help="Investment Linked Policy Sustainability")
        with col_sb2:
            p_cov = st.number_input(t["coverage"], min_value=0.0, step=1000.0)
            p_max_age = st.number_input(t["max_age"], min_value=0, max_value=100, value=80)
            
        p_rem = st.text_area(t["remarks"], height=80)
        
        submitted = st.form_submit_button(t["add_btn"])
        
        if submitted:
            if p_name:
                st.session_state.policies.append({
                    t["policy_name"]: p_name,
                    t["policy_company"]: p_company,
                    t["policy_type"]: p_type,
                    t["premium"]: p_prem,
                    t["coverage"]: p_cov,
                    t["sustainability"]: p_sust if p_sust > 0 else "-", # 如果填0显示-
                    t["max_age"]: p_max_age,
                    t["remarks"]: p_rem
                })
                st.success("✅ Added!")
            else:
                st.error("Please enter policy name.")

    # 清空按钮
    if len(st.session_state.policies) > 0:
        if st.button(t["clear_btn"]):
            st.session_state.policies = []
            st.rerun()

# --- 4. 主界面：报告显示 ---
st.title(f"{t['title']}")
if c_name:
    st.subheader(f"{t['client_profile']}: {c_name} ({c_age})")
st.markdown(f"Date: {datetime.now().strftime('%Y-%m-%d')}")
st.markdown("---")

# 如果还没有保单
if len(st.session_state.policies) == 0:
    st.info(t["empty_msg"])

else:
    # 转换为 DataFrame
    df = pd.DataFrame(st.session_state.policies)
    
    # 顶部关键指标卡片
    col1, col2, col3 = st.columns(3)
    total_prem = df[t["premium"]].sum()
    total_cov = df[t["coverage"]].sum()
    
    with col1:
        st.metric(label=t["total_premium"], value=f"RM {total_prem:,.0f}")
    with col2:
        st.metric(label=t["total_coverage"], value=f"RM {total_cov:,.0f}")
    with col3:
        st.metric(label="Total Policies", value=len(df))
        
    # --- 表格展示 ---
    st.subheader(t["table_header"])
    # 样式优化：高亮显示持久性和最高续保年龄
    st.dataframe(
        df, 
        use_container_width=True, 
        hide_index=True,
        column_config={
            t["premium"]: st.column_config.NumberColumn(format="RM %.0f"),
            t["coverage"]: st.column_config.NumberColumn(format="RM %.0f"),
        }
    )
    
    # --- 图表分析 ---
    st.subheader(t["chart_title"])
    
    # 柱状图：展示每份保单的保费 vs 保障
    chart_df = df.melt(id_vars=[t["policy_name"]], value_vars=[t["premium"], t["coverage"]], var_name="Type", value_name="Value")
    
    fig = px.bar(
        chart_df, 
        x=t["policy_name"], 
        y="Value", 
        color="Type", 
        barmode="group",
        text_auto='.2s',
        color_discrete_sequence=["#FF6B6B", "#4ECDC4"] # 红色代表保费，青色代表保障
    )
    fig.update_layout(xaxis_title="", yaxis_title="RM")
    st.plotly_chart(fig, use_container_width=True)
    
    # --- 散点图：持久性警告 (可选高级图表) ---
    # 如果有填写持久性数据，显示一个简单的警告图
    if pd.to_numeric(df[t["sustainability"]], errors='coerce').sum() > 0:
        st.caption("⚠️ Sustainability Check (持久性检查)")
        # 简单处理：过滤出有数字的行
        sust_df = df[pd.to_numeric(df[t["sustainability"]], errors='coerce') > 0].copy()
        if not sust_df.empty:
            st.bar_chart(sust_df.set_index(t["policy_name"])[t["sustainability"]])
            st.caption(f"* {t['sustainability']}")

    # --- 下载区域 ---
    st.markdown("---")
    st.subheader(t["download_header"])
    
    csv = df.to_csv(index=False).encode('utf-8')
    file_name = f"Review_{c_name}_{datetime.now().strftime('%Y%m%d')}.csv"
    
    st.download_button(
        label=t["download_btn"],
        data=csv,
        file_name=file_name,
        mime='text/csv'
    )

st.caption(t["footer"])
